# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI Pipeline

on:
  pull_request:
    branches:
    - develop
    paths:
    # Trigger only when there are changes to any code (as opposed to READMEs etc)
    - 'pipelines/**'
    - 'scheduler/**'
    - '!pipelines/README.md'
    - '!scheduler/README.md'

jobs:
  build_and_test:
    strategy:
      matrix:
        dir: [ pipelines, scheduler ]
    runs-on: ubuntu-latest
    name: Build and test ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v2
        with:
          # ref: refs/heads/develop
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - id: build
        name: Build and test ${{ matrix.dir }}
        shell: bash
        run: |
          set -e

          cd ${{ matrix.dir }}
          npm ci
          npm run build
          npm run test